version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=kotlin-graphql
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./init-users.sh:/docker-entrypoint-initdb.d/init-users.sh:ro
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    ports:
      - 27017:27017
    restart: unless-stopped

volumes:
  mongodb:
  mongoconfig: